name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Download dependencies and more
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt install -y build-essential git gcc gdb libsdl2-dev
        
      - name: Build and install Nelua
        run: |
          git clone https://github.com/edubart/nelua-lang.git
          sudo make -C nelua-lang/ install
      
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: 0.8.0
          
      - name: Clone and build ZLNL
        run: |
          git clone https://github.com/darltrash/zlnl
          cd zlnl
          make build
          
      - name: Upload the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Linux GLIBC x86_64 build
          path: ./zlnl
